---
apiVersion: v1
kind: ServiceAccount
metadata:
  annotations:
    iam.gke.io/gcp-service-account: {{ .Values.iam.google_service_account_name }}
  name: {{ .Values.iam.k8s_service_account_name }}
  namespace: {{ .Values.namespace }}
  labels:
    "app.kubernetes.io/managed-by": "Helm"
    "meta.helm.sh/release-name": "{{ .Release.Name }}"
    "meta.helm.sh/release-namespace": "{{ .Values.namespace }}"
---
{{ if .Values.psp.enabled }}

# neuron strict psp RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ .Values.psp.cluster_role_binding }}
  namespace: {{ .Values.namespace }}
  labels:
    "app.kubernetes.io/managed-by": "Helm"
    "meta.helm.sh/release-name": "{{ .Release.Name }}"
    "meta.helm.sh/release-namespace": "{{ .Values.namespace }}"
subjects:
# For all service accounts in a particular namespace
- apiGroup: rbac.authorization.k8s.io
  kind: Group
  name: system:serviceaccounts
  namespace: {{ .Values.namespace }}
roleRef:
  kind: ClusterRole
  name: {{ .Values.psp.cluster_role }}
  apiGroup: rbac.authorization.k8s.io
  
{{- end }}

---