# ingress
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  namespace: {{ .Values.namespace }}
  name: {{ .Values.ingress.name }}
  annotations:
    kubernetes.io/ingress.class: "gce"
    kubernetes.io/ingress.global-static-ip-name: {{ .Values.ingress.static_ip_name }} # config for global static IP public
    networking.gke.io/managed-certificates: "production-managed-cert"
    networking.gke.io/v1beta1.FrontendConfig: "{{ .Values.nginx.service_name }}"
spec:
  rules:
    - host: "www.notejamdemo.com"
      http:
        paths:
        - path: "/*"
          pathType: ImplementationSpecific # (Exact,Prefix or ImplementationSpecific)
          backend:
            service:
              name: {{ .Values.nginx.service_name }}
              port:
                number: {{ .Values.nginx.port }}