---
# DB secret
apiVersion: v1
kind: Secret
type: Opaque
metadata:
  annotations:
    meta.helm.sh/release-name: {{ .Release.Name }}
    meta.helm.sh/release-namespace: {{ .Values.namespace }}
  labels:
    app.kubernetes.io/managed-by: Helm
  name: {{ .Values.secrets.secret_name }}
  namespace: {{ .Values.namespace }}
data:  
    db-name: {{ print $lm.db.db_name | b64enc }}
    db-password: {{ $lm.db.db_password }}
    db-host: {{ $lm.db.db_host | b64enc }}
    db-username: {{ $lm.db.db_username }}
  

---
# front end tls cert data

apiVersion: v1
data:
  tls.crt: {{ .Values.ingress.tls_crt }}
  tls.key: {{ .Values.ingress.tls_key }}
kind: Secret
metadata:
  name: {{ .Values.ingress.tls_secret_name }}
  namespace: {{ .Values.namespace }}
type: kubernetes.io/tls

---